# supabase/config.toml
# Este arquivo é usado para configurar as definições de implantação das Supabase Edge Functions.

[[functions]]
name = "mercadopago-webhook"
verify_jwt = false # IMPORTANTE: Definido como false para permitir webhooks do Mercado Pago sem JWT