// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qnrqsbvhrtlicxklmhjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucnFzYnZocnRsaWN4a2xtaGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDgwNjEsImV4cCI6MjA3MTIyNDA2MX0.r7RyzHXGlIvkZ3Z1T_7VqZ4jG8Kbag2pSdVYGnvyOjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);